### ISSUE TITLE
HashMap serialization does not support other hasher's

### ISSUE THREAD

**Issue by Mythra** [bearcove/merde#87]
Hey,

I've been working on adopting merde into a project I've been working on, and this project makes extensive use of [fnv](https://crates.io/crates/fnv), and it's type `FnvHashMap`, which is really just: `pub type FnvHashMap<K, V> = HashMap<K, V, FnvBuildHasher>;` because of it's performance characteristics with smaller keys. Unfortunately when trying to implement `JsonSerialize` with types like this, you get an error message like:

```
error[E0277]: the trait bound `HashMap<std::string::String, merde::Value<'args>, BuildHasherDefault<FnvHasher>>: JsonSerialize` is not satisfied
    --> src/ser.rs:1235:22
     |
1235 |         guard.pair("args", &self.args_merde);
     |                            ^^^^^^^^^^^^^^^^ the trait `JsonSerialize` is not implemented for `HashMap<std::string::String, merde::Value<'args>, BuildHasherDefault<FnvHasher>>`
     |
     = help: the trait `JsonSerialize` is implemented for `HashMap<K, V>`
     = note: required for the cast from `&HashMap<std::string::String, merde::Value<'args>, BuildHasherDefault<FnvHasher>>` to `&dyn JsonSerialize`
```

Changing this type to a regular hashmap allows the code to compile. I know merde isn't super focused on performance, or every case, so I'm curious would there be any possibility to support custom hashers? or is this something better left to "just use a regular hashmap, and if you want something to support custom hashers use another crate".

**Comment by fasterthanlime** [comment]
I definitely want to support custom hashers (but not pull them in by default). I thought it was already the case, in fact.

I would accept a PR for that if you beat me to it!

**Comment by fasterthanlime** [comment]
merde 6.1.0 is being released, which includes that feature :)

cf. https://github.com/bearcove/merde/pull/88
